app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /about

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_registration_register:
    path:  /register
    methods: [GET, POST]
    defaults:  { _controller: AppBundle:Default:register }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

customer_registration:
    path:  /register/customer
    defaults: { _controller: AppBundle:RegistrationCustomer:register }

shop_owner_registration:
    path:  /register/shop-owner
    defaults: { _controller: AppBundle:RegistrationShopOwner:register }